# Generated by Django 5.2.17 on 2026-09-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_company_alter_lead_next_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('Organic', 'Organic'), ('Junk', 'Junk')], db_index=True, default='Organic', help_text='Classification: Organic or Junk', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='next_followup',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Google', 'Google'), ('Website', 'Website'), ('Organic', 'Organic')], db_index=True, default='Website', help_text='Channel where lead originated', max_length=50),
        ),
    ]
