# Generated by Django 5.2.17 on 2026-09-29 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Paid', 'Paid')], db_index=True, default='Draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], db_index=True, max_length=10),
        ),
    ]
